name: heart_rate_monitor
description: Heart Rate Monitor For You.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  font_awesome_flutter: ^10.2.1
  cloud_firestore: ^4.0.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  provider: ^6.0.4
  intl: ^0.17.0
  pdf: ^3.8.0
  printing: ^5.9.3
  path_provider: ^2.0.12
  open_file: ^3.2.1
  fl_chart: ^0.60.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/Segoe UI.ttf
        - asset: assets/fonts/Segoe UI Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf